sudo: false
language: node_js
node_js:
  - node
install:
  - npm ci
cache:
  directories:
  - node_modules
script: echo "Running tests against $(node -v)..."
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
before_deploy:
  - cd $TRAVIS_BUILD_DIR
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
